{"message":"reponse error to user","stack":"TypeError: User.createANewUser is not a function\n    at E:\\workspace\\node_app\\routes\\users.js:27:35\n    at router.route.get.post (E:\\workspace\\node_app\\routes\\users.js:37:11)\n    at Layer.handle [as handle_request] (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at next (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\route.js:131:14)\n    at Route.dispatch (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\index.js:335:12)","level":"error","timestamp":"2017-09-20T13:21:54.832Z"}
{"message":"reponse error to user","stack":"TypeError: User.createANewUser is not a function\n    at E:\\workspace\\node_app\\routes\\users.js:27:35\n    at router.route.get.post (E:\\workspace\\node_app\\routes\\users.js:37:11)\n    at Layer.handle [as handle_request] (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at next (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\route.js:131:14)\n    at Route.dispatch (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\index.js:335:12)","level":"error","timestamp":"2017-09-20T13:36:12.513Z"}
{"message":"reponse error to user","stack":"TypeError: User.createANewUser is not a function\n    at E:\\workspace\\node_app\\routes\\users.js:27:35\n    at router.route.get.post (E:\\workspace\\node_app\\routes\\users.js:37:11)\n    at Layer.handle [as handle_request] (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at next (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\route.js:131:14)\n    at Route.dispatch (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\index.js:335:12)","level":"error","timestamp":"2017-09-20T14:02:18.996Z"}
{"message":"reponse error to user","stack":"TypeError: User.createANewUser is not a function\n    at E:\\workspace\\node_app\\routes\\users.js:27:35\n    at router.route.get.post (E:\\workspace\\node_app\\routes\\users.js:37:11)\n    at Layer.handle [as handle_request] (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at next (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\route.js:131:14)\n    at Route.dispatch (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (E:\\workspace\\node_app\\node_modules\\express\\lib\\router\\index.js:335:12)","level":"error","timestamp":"2017-09-20T14:02:40.166Z"}
{"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: node-app.users index: name_1 dup key: { : \"banana\" }","op":{"name":"banana","age":20,"password":"�L\u0001�LI�8F,���/\u0004\"�0G�����\u000e��T��I\u000b\t�\u0000LĚP�\u0006��\u001f�!M3�\nұ�}ZG�70Q3���ϣ&�r�\u0002�\\a���H�\u0007͏�\u0013��^��˿� �n{U�\n�.O\u0007$�7EO/\u001a��\u0014 jw��8��/\u000e)c,\u0013�1��R���\u001d\u000f�H�>�\u000e;L��d\"�,l�%j����GB�\u001b�\u001da\u0002m\u001c�N��@���?�V�J\n\u0013\u001d\"d����k\u0005�d\u0011��A��AP�\u000e��:��hQ:\u0005�|T�>�;\u0011E����\tC3�K\u000f�hdW[�q��\u0003�\r�\u0012\u00152�r��kP�_>Es�%�����*\u00183\u0003{��W�+�w�a�\u0019Swi�+\"4\u0006k��\u001c�3w%�񘮟\u0016�\u0004��r�x� '5��\u0006��b��F��ʜUj�(��:�-��a�{�y�ph��Pk�bQ1�\t����]\u0016q�\u000b\u0000�l��N\u001f��G���\u0006�\t��$ ɳ�8�їٕ�G�ت���`���;e=Ax\u0004\fн-��׷\u0002��w(l�f&v��\u0018b\u000fE���M�p�\u0016Ph3(�é�d���Z�qP;�\u0019�$�Q�����X�Q���Uz,vt�iA\u0019\"\u0006_We�]���\u000e�\u0000�","_id":"59c2755752a4e311e41d0995","__v":0}}
{"message":"reponse error to user","stack":"ReferenceError: OPCode is not defined\n    at DuplicatedNameError.BasehttpError (E:\\workspace\\node_app\\error.js:4:23)\n    at ValidationError (E:\\workspace\\node_app\\error.js:26:9)\n    at DuplicatedNameError (E:\\workspace\\node_app\\error.js:33:9)\n    at user.save.catch.e (E:\\workspace\\node_app\\models\\mongoose\\user.js:34:27)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)","level":"error","timestamp":"2017-09-20T14:04:07.438Z"}
{"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: node-app.users index: name_1 dup key: { : \"banana\" }","op":{"name":"banana","age":20,"password":"�L\u0001�LI�8F,���/\u0004\"�0G�����\u000e��T��I\u000b\t�\u0000LĚP�\u0006��\u001f�!M3�\nұ�}ZG�70Q3���ϣ&�r�\u0002�\\a���H�\u0007͏�\u0013��^��˿� �n{U�\n�.O\u0007$�7EO/\u001a��\u0014 jw��8��/\u000e)c,\u0013�1��R���\u001d\u000f�H�>�\u000e;L��d\"�,l�%j����GB�\u001b�\u001da\u0002m\u001c�N��@���?�V�J\n\u0013\u001d\"d����k\u0005�d\u0011��A��AP�\u000e��:��hQ:\u0005�|T�>�;\u0011E����\tC3�K\u000f�hdW[�q��\u0003�\r�\u0012\u00152�r��kP�_>Es�%�����*\u00183\u0003{��W�+�w�a�\u0019Swi�+\"4\u0006k��\u001c�3w%�񘮟\u0016�\u0004��r�x� '5��\u0006��b��F��ʜUj�(��:�-��a�{�y�ph��Pk�bQ1�\t����]\u0016q�\u000b\u0000�l��N\u001f��G���\u0006�\t��$ ɳ�8�їٕ�G�ت���`���;e=Ax\u0004\fн-��׷\u0002��w(l�f&v��\u0018b\u000fE���M�p�\u0016Ph3(�é�d���Z�qP;�\u0019�$�Q�����X�Q���Uz,vt�iA\u0019\"\u0006_We�]���\u000e�\u0000�","_id":"59c275d7c656fb10689d4948","__v":0}}
{"message":"reponse error to user","stack":"ValidationError: Error validation params:username ,reason:duplicate user name: user\n    at user.save.catch.e (E:\\workspace\\node_app\\models\\mongoose\\user.js:34:27)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)","OPCode":200001,"httpCode":200000,"httpMsg":"这个昵称已经被使用了","name":"ValidationError","level":"error","timestamp":"2017-09-20T14:06:15.896Z"}
